name: Deploy Azure Function App

on:
  push:
    branches:
      - main  # deploy on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Optional: Run tests
      - name: Run tests
        run: npm test || echo "No tests defined"

      # 5. Deploy using Zip Deploy
      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cyberscorecalculator-a9fra5d6cgbpdqfa'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: '.'