name: Azure Functions CI/CD

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests (optional)
      run: npm test || echo "No tests defined"

    - name: Archive function app
      run: zip -r functionapp.zip .

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: 'CyberScoreCalculator'
        package: 'functionapp.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
