name: Deploy Azure Function App

on:
  push:
    branches:
      - main  # deploy whenever you push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Optional: Run tests
      - name: Run tests
        run: npm test || echo "No tests defined"

      # 5. Deploy to Azure Functions using publish profile
      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: 'CyberScoreCalculator'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: '.'  # Deploy the current folder
